# Generated by Django 4.1 on 2022-09-05 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('narx', models.IntegerField()),
                ('kelgan_sana', models.DateField()),
                ('nashiryoti', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nashiryot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('manzil', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sotuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('tel', models.PositiveSmallIntegerField()),
                ('sotuv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yangi.kitob')),
            ],
        ),
    ]
