# Generated by Django 4.1 on 2022-09-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yangi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nashiryot',
        ),
        migrations.RemoveField(
            model_name='sotuvchi',
            name='sotuv',
        ),
        migrations.DeleteModel(
            name='Kitob',
        ),
        migrations.DeleteModel(
            name='Sotuvchi',
        ),
    ]
