# Generated by Django 4.1 on 2022-09-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangi', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bitiruvchi',
            field=models.BooleanField(default=False),
        ),
    ]
